
[server]
addr = "127.0.0.1"
port = "8082"

[server_monitor]
addr = "127.0.0.1"
port = "3782"

[raft]
addr = "127.0.0.1"
port = "12002"
peers = ["127.0.0.1:12002", "127.0.0.1:12001",  "127.0.0.1:12003"]
peer_storage = "raft2/raft_peer_storage"
snapshot_storage = "raft2/raft_snapshot_storage"
store_backend = "boltdb"
storage_backend_path = "raft2/storage_backend_path"
raft_log_path = "raft2/raft_log_path"
apply_log_path = "raft2/apply_log_path"
enable_single_node = false

[rpc]
addr = "127.0.0.1"
port = "32125"

[log]

log_dir = "raft2/logs"
log_name = "raft_access_log"
log_level = "debug"
